# okay. so the aim here is to try to replicate the word frequency analysis

library(dplyr)

d <- read.csv("~/work/phd/eyetracking/data/data/Jun_data/augmented_English_4_word_info.csv")
colnames(d)

d$thiss
colnames(d)

head(d$wordAt_l)
head(d$word_l)
unique(d$wordAt_l)
d$wordf

nrow(filter(d, is.na(d$bigram_frequencies_l))) / nrow(d)

head(d$bigram_frequencies_l)


head(d$wordAt_l)
head(d$word_l)
cor(d$word_l, d$normalized_norvig_wordfreq_l)
head(d$word_l)
head(d$normalized_norvig_wordfreq_l)

fname_l <- "~/work/phd/eyetracking/data/data/Jun_data/English_wordfreq_l.csv"
fname_r <- "~/work/phd/eyetracking/data/data/Jun_data/English_wordfreq_r.csv"

l <- read.csv(fname_l)
r <- read.csv(fname_r)
colnames(l)
colnames(r)
head(l)
head(r)
hist(l$first_gaze_duration_l) 
hist(r$first_gaze_duration_r) 
hist(l$total_gaze_duration_l)
hist(r$total_gaze_duration_r) 
cor(l$first_gaze_duration_l, l$wordfreq_l) 
l["log_wordfreq_l"] <- log(l$wordfreq_l)

cor(r$first_gaze_duration_r, r$wordfreq_r)
mean(l$wordfreq_l)
sd(l$wordfreq_l)
hist(l$wordfreq_l)

ltemp <- filter(l, l$wordfreq_l > 0.0001)
nrow(ltemp) / nrow(l)
ltemp$log_wordfreq_l <- log(ltemp$wordfreq_l)
head(ltemp$log_wordfreq_l)
cor(ltemp$log_wordfreq_l, ltemp$first_gaze_duration_l)
cor(r$first_gaze_duration_r, r$wordfreq_r)
cor(l$wordfreq_l, l$total_gaze_duration_l) 
cor(r$wordfreq_r, r$total_gaze_duration_r) 

cor(l$word_information_l, l$first_gaze_duration_l) 
cor(l$word_information_l, l$total_gaze_duration_l) 
cor(r$word_information_r, r$first_gaze_duration_r)
cor(r$word_information_r, r$total_gaze_duration_r) 
cor(l$word_information_l, l$wordfreq_l) 
cor(l$norvig_wordfreq_l, l$wordfreq_l)
n <- subset(l, !is.na(l$norvig_wordfreq_l))
cor(n$norvig_wordfreq_l, n$word_information_l)
cor(n$norvig_wordfreq_l, n$wordfreq_l)
cor(l$bigram_frequencies_l, l$wordfreq_l)
b <- subset(l, !is.na(l$bigram_frequencies_l))
cor(b$bigram_frequencies_l, b$wordfreq_l) 
cor(b$bigram_frequencies_l, b$first_gaze_duration_l) 
cor(b$bigram_frequencies_l, b$total_gaze_duration_l)  
nrow(l)
br <- subset(r, !is.na(r$bigram_frequencies_r))
cor(br$bigram_frequencies_r, br$wordfreq_r
cor(br$bigram_frequencies_r, br$first_gaze_duration_r)
cor(br$bigram_frequencies_r, br$total_gaze_duration_r)
hist(br$bigram_frequencies_r)
filt <- subset(br ,br$bigram_frequencies_r < 1000)
hist(filt$bigram_frequencies_r).
cor(filt$bigram_frequencies_r, filt$total_gaze_duration_r)
cor(filt$bigram_frequencies_r, filt$first_gaze_duration_r)

hist(b$bigram_frequencies_l)
hist(b$total_gaze_duration_l)
hist(l$first_gaze_duration_l)
hist(l$norvig_wordfreq_l) 
max(!is.na(l$norvig_wordfreq_l))
sd(l$total_gaze_duration_l)

fl <- subset(l, l$total_gaze_duration_l < 60000)
nrow(fl) / nrow(l)
hist(fl$total_gaze_duration_l) 
hist(r$total_gaze_duration_r)
fr <- subset(r, r$total_gaze_duration_r < 60000)
hist(fr$total_gaze_duration_r)
cor(fr$total_gaze_duration_r, fr$wordfreq_r)
cor(fl$total_gaze_duration_l, fl$wordfreq_l)
cor(fr$first_gaze_duration_r, fr$wordfreq_r)
cor(fr$wordfreq_r, fr$first_gaze_duration_r)
cor(fl$first_gaze_duration_l, fl$wordfreq_l)
cor(l$first_gaze_duration_l, l$wordfreq_l)
cor(n$first_gaze_duration_l, n$norvig_wordfreq_l)
n$log_norvig <- log(n$norvig_wordfreq_l)
mean(n$log_norvig)
hist(n$log_norvig)
hist(n$norvig_wordfreq_l)
cor(n$log_norvig, n$first_gaze_duration_l)

lf <- subset(l, l$wordfreq_l > 0.0001)
cor(lf$first_gaze_duration_l, lf$wordfreq_l)
lf$log_freq <- log(lf$wordfreq_l)
mean(lf$log_freq)
hist(lf$log_freq)
cor(lf$first_gaze_duration_l, lf$log_freq) 
hist(l$wordfreq_l)
mean(l$word_information_l)
hist(l$word_information_l)
head(l$word_information_l)
range(l$word_information_l)
sd(l$word_information_l)
nrow(subset(l, l$word_information_l < 0)) / nrow(l)
cor(i$word_information_l, i$first_gaze_duration_l) 
cor(i$word_information_l, i$total_gaze_duration_l)
hist(l$bigram_frequencies_l)
bl <- subset(l, !is.na(l$bigram_frequencies_l))
nrow(bl) / nrow(l)
nrow(bl)
hist(bl$bigram_frequencies_l)
mean(bl$bigram_frequencies_l)
bl$log_bigrams <- log(bl$bigram_frequencies_l)
hist(bl$log_bigrams)
head(bl$log_bigrams)
cor(bl$first_gaze_duration_l, bl$log_bigrams)
cor(bl$total_gaze_duration_l, bl$log_bigrams)

cor(i$log_ingo, i$wordfreq_l)
cor(i$word_information_l, i$wordfreq_l) 
cor(i$word_information_l, i$norvig_wordfreq_l) 
cor(n$norvig_wordfreq_l, n$wordfreq_l)
cor(n$log_norvig, n$wordfreq_l)

cor(i$log_ingo, i$first_gaze_duration_l)
cor(i$wordfreq_l, i$first_gaze_duration_l)